# Generated by Django 4.1 on 2022-09-20 07:43

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_alter_post_options_post_shared_body_post_shared_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_on',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_user',
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image-profile'),
            preserve_default=False,
        ),
    ]
