# Generated by Django 4.1 on 2022-10-07 12:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0021_alter_messagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.jpg', max_length=255, null=True, verbose_name='image-profile'),
        ),
    ]
